# This is not a python file, but a configuration file.
# No need of structured data, just a simple key-value pair.
# We can add multiple variables here as per our need.
# We can use this file to store configuration settings for our application.

[Common info] #this is a section header
baseURL=https://admin-demo.nopcommerce.com/admin/
useremail=admin@yourstore.com
password=admin
